import enum


class Tokens(enum.Enum):
    LEFT_PAREN = enum.auto()
    RIGHT_PAREN = enum.auto()
    LEFT_CURLY = enum.auto()
    RIGHT_CURLY = enum.auto()
    LEFT_SQUARE = enum.auto()
    RIGHT_SQUARE = enum.auto()

    PLUS = enum.auto()
    MINUS = enum.auto()
    ASTERISK = enum.auto()
    SLASH = enum.auto()
    SLASH_SLASH = enum.auto()
    PERCENT = enum.auto()
    CARET = enum.auto()
    DOT = enum.auto()
    QUESTION = enum.auto()

    EXCLAMATION = enum.auto()
    AMPERSAND = enum.auto()
    BAR = enum.auto()
    COLON = enum.auto()
    SEMI_COLON = enum.auto()
    COMMA = enum.auto()

    EQUAL = enum.auto()
    EQUAL_EQUAL = enum.auto()
    NOT_EQUAL = enum.auto()
    GREATER = enum.auto()
    GREATER_EQUAL = enum.auto()
    LESS = enum.auto()
    LESS_EQUAL = enum.auto()

    IDENTIFIER = enum.auto()
    STRING = enum.auto()
    RUNE = enum.auto()
    INTEGER = enum.auto()
    FLOAT = enum.auto()
    BOOLEAN = enum.auto()
    TYPE = enum.auto()

    AND = enum.auto()
    OR = enum.auto()
    XOR = enum.auto()
    NOT = enum.auto()
    LEFT_SHIFT = enum.auto()
    RIGHT_SHIFT = enum.auto()

    IF = enum.auto()
    ELSE = enum.auto()
    WHILE = enum.auto()
    FOR = enum.auto()
    BREAK = enum.auto()
    CONTINUE = enum.auto()
    MATCH = enum.auto()
    CASE = enum.auto()

    UNWRAP = enum.auto()
    HANDLE = enum.auto()

    FUNCTION = enum.auto()
    RETURN = enum.auto()
    CALL = enum.auto()
    DO = enum.auto()
    WITH = enum.auto()

    CONST = enum.auto()
    STATIC = enum.auto()
    MUTABLE = enum.auto()
    SET = enum.auto()

    STRUCT = enum.auto()
    IMPLEMENT = enum.auto()
    ENUM = enum.auto()
    UNION = enum.auto()

    REQUIRE = enum.auto()
    DEFER = enum.auto()
    END = enum.auto()

    POP = enum.auto()
    DROP = enum.auto()
    DUP = enum.auto()
    OVER = enum.auto()
    ROT = enum.auto()
    SWAP = enum.auto()
