//! Build script for `yarrow-core`.
//!
//! - Embeds the std library under `lib/std/` into the binary.
//! - Builds / records AOT runtime static archives for the host and, when the
//!   Rust target is installed, the Stage 26 cross triple(s).

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    embed_std_modules();
    record_aot_runtime_archives();
}

fn embed_std_modules() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let std_dir = Path::new(&manifest).join("lib").join("std");
    println!("cargo:rerun-if-changed={}", std_dir.display());

    let mut modules: Vec<(String, String)> = Vec::new();
    walk_yar(&std_dir, &std_dir, &mut modules);

    let mut out = String::from("// @generated by build.rs - do not edit.\n");
    out.push_str("pub const STD_MODULES: &[(&str, &str)] = &[\n");
    for (name, file) in &modules {
        out.push_str(&format!(
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/lib/std/{file}\"))),\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("std_modules.rs"), out).unwrap();
}

fn record_aot_runtime_archives() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let aot_manifest = manifest.join("../yarrow-runtime/aot/Cargo.toml");
    println!("cargo:rerun-if-changed={}", aot_manifest.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest.join("../yarrow-runtime").display()
    );
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=TARGET");
    println!("cargo:rerun-if-env-changed=YARROW_BUILD_CROSS_AOT");

    let host_target = env::var("TARGET").unwrap();
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let aot_target_dir = PathBuf::from(env::var("OUT_DIR").unwrap()).join("aot-target");
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());

    // Always build the archive matching the crate TARGET (usually the host).
    let host_archive = build_aot_archive(&cargo, &aot_manifest, &aot_target_dir, &profile, None)
        .unwrap_or_else(|e| panic!("{e}"));
    println!(
        "cargo:rustc-env=YARROW_RUNTIME_AOT_ARCHIVE={}",
        host_archive.display()
    );

    // Optional cross archives: other linux-gnu arch when that Rust target exists.
    let mut table = format!("{host_target}={}", host_archive.display());
    let cross_enabled = env::var_os("YARROW_BUILD_CROSS_AOT").is_some_and(|v| v != "0");
    if cross_enabled {
        for cross in cross_triples_for(&host_target) {
            match build_aot_archive(
                &cargo,
                &aot_manifest,
                &aot_target_dir,
                &profile,
                Some(cross),
            ) {
                Ok(path) => {
                    table.push(';');
                    table.push_str(cross);
                    table.push('=');
                    table.push_str(&path.display().to_string());
                    println!("cargo:warning=built AOT runtime archive for {cross}");
                }
                Err(msg) => {
                    // Soft-fail: object emit for the triple still works; link needs an override.
                    println!("cargo:warning=skipping AOT archive for {cross}: {msg}");
                }
            }
        }
    }
    println!("cargo:rustc-env=YARROW_RUNTIME_AOT_ARCHIVE_TABLE={table}");
}

fn cross_triples_for(host: &str) -> Vec<&'static str> {
    // Stage 26: one additional linux-gnu arch.
    if host.starts_with("x86_64-") && host.contains("linux") && host.contains("gnu") {
        vec!["aarch64-unknown-linux-gnu"]
    } else if host.starts_with("aarch64-") && host.contains("linux") && host.contains("gnu") {
        vec!["x86_64-unknown-linux-gnu"]
    } else {
        Vec::new()
    }
}

fn build_aot_archive(
    cargo: &str,
    aot_manifest: &Path,
    aot_target_dir: &Path,
    profile: &str,
    target: Option<&str>,
) -> Result<PathBuf, String> {
    let mut cmd = Command::new(cargo);
    cmd.arg("build")
        .arg("--manifest-path")
        .arg(aot_manifest)
        .arg("--target-dir")
        .arg(aot_target_dir);
    if profile == "release" {
        cmd.arg("--release");
    }
    if let Some(t) = target {
        cmd.arg("--target").arg(t);
    }
    let status = cmd
        .status()
        .map_err(|e| format!("failed to spawn `{cargo}` to build yarrow_runtime_aot: {e}"))?;
    if !status.success() {
        return Err(format!(
            "building yarrow_runtime_aot{} failed with {status}",
            target.map(|t| format!(" for {t}")).unwrap_or_default()
        ));
    }

    let profile_name = if profile == "release" {
        "release"
    } else {
        "debug"
    };
    let profile_dir = if let Some(t) = target {
        aot_target_dir.join(t).join(profile_name)
    } else {
        aot_target_dir.join(profile_name)
    };
    let archive = if target.is_some_and(|t| t.contains("windows"))
        || (target.is_none() && env::var("TARGET").is_ok_and(|t| t.contains("windows")))
    {
        profile_dir.join("yarrow_runtime_aot.lib")
    } else {
        profile_dir.join("libyarrow_runtime_aot.a")
    };
    if !archive.is_file() {
        return Err(format!("expected AOT archive at {}", archive.display()));
    }
    Ok(archive)
}

/// Recursively collect `*.yar` files under `dir`, recording each as
/// `(dotted module name, path relative to the std dir)`.
fn walk_yar(dir: &Path, std_dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut files: Vec<String> = entries
        .filter_map(|e| e.ok())
        .filter(|e| {
            let p = e.path();
            p.is_file() && p.extension().is_some_and(|x| x == "yar")
        })
        .map(|e| {
            e.path()
                .strip_prefix(std_dir)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();
    files.sort();
    for file in files {
        let dotted = file.strip_suffix(".yar").unwrap().replace('/', ".");
        out.push((format!("std.{dotted}"), file));
    }
    if let Ok(entries) = fs::read_dir(dir) {
        let mut subdirs: Vec<_> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.path())
            .collect();
        subdirs.sort();
        for sub in subdirs {
            walk_yar(&sub, std_dir, out);
        }
    }
}
