//! Build script for `yarrow-core`.
//!
//! - Embeds the std library under `lib/std/` into the binary.
//! - Builds / records the AOT host-runtime static archive for [`linkable_archive`].

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    embed_std_modules();
    record_aot_runtime_archive();
}

fn embed_std_modules() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let std_dir = Path::new(&manifest).join("lib").join("std");
    println!("cargo:rerun-if-changed={}", std_dir.display());

    let mut modules: Vec<(String, String)> = Vec::new();
    walk_yar(&std_dir, &std_dir, &mut modules);

    let mut out = String::from("// @generated by build.rs - do not edit.\n");
    out.push_str("pub const STD_MODULES: &[(&str, &str)] = &[\n");
    for (name, file) in &modules {
        out.push_str(&format!(
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/lib/std/{file}\"))),\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("std_modules.rs"), out).unwrap();
}

fn record_aot_runtime_archive() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let aot_manifest = manifest.join("../yarrow-runtime/aot/Cargo.toml");
    println!("cargo:rerun-if-changed={}", aot_manifest.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest.join("../yarrow-runtime").display()
    );
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=TARGET");

    let target = env::var("TARGET").unwrap();
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    // Nested cargo build in a private target dir avoids locking the parent
    // target/ (which would deadlock under the outer cargo).
    let aot_target = PathBuf::from(env::var("OUT_DIR").unwrap()).join("aot-target");
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    let mut cmd = Command::new(&cargo);
    cmd.arg("build")
        .arg("--manifest-path")
        .arg(&aot_manifest)
        .arg("--target-dir")
        .arg(&aot_target);
    if profile == "release" {
        cmd.arg("--release");
    }
    let status = cmd.status().unwrap_or_else(|e| {
        panic!("failed to spawn `{cargo}` to build yarrow_runtime_aot: {e}");
    });
    if !status.success() {
        panic!("building yarrow_runtime_aot failed with {status}");
    }

    let profile_dir = aot_target.join(if profile == "release" {
        "release"
    } else {
        "debug"
    });
    let archive = if target.contains("windows") {
        profile_dir.join("yarrow_runtime_aot.lib")
    } else {
        profile_dir.join("libyarrow_runtime_aot.a")
    };
    if !archive.is_file() {
        panic!("expected AOT archive at {}", archive.display());
    }
    println!(
        "cargo:rustc-env=YARROW_RUNTIME_AOT_ARCHIVE={}",
        archive.display()
    );
}

/// Recursively collect `*.yar` files under `dir`, recording each as
/// `(dotted module name, path relative to the std dir)`.
fn walk_yar(dir: &Path, std_dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut files: Vec<String> = entries
        .filter_map(|e| e.ok())
        .filter(|e| {
            let p = e.path();
            p.is_file() && p.extension().is_some_and(|x| x == "yar")
        })
        .map(|e| {
            e.path()
                .strip_prefix(std_dir)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();
    files.sort();
    for file in files {
        let dotted = file.strip_suffix(".yar").unwrap().replace('/', ".");
        out.push((format!("std.{dotted}"), file));
    }
    if let Ok(entries) = fs::read_dir(dir) {
        let mut subdirs: Vec<_> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.path())
            .collect();
        subdirs.sort();
        for sub in subdirs {
            walk_yar(&sub, std_dir, out);
        }
    }
}
