//! Build script for `yarrow-core`.
//!
//! Embeds the std library (pure-Yarrow source files under `lib/std/`) into
//! the binary. Each `lib/std/<name>.yar` file becomes the module
//! `std.<name>`; sub-folder files (`lib/std/a/b.yar`) map to `std.a.b`. The
//! generated table replaces the hand-written `STD_MODULES` const that used
//! to live in `compiler/modules.rs`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let std_dir = Path::new(&manifest).join("lib").join("std");
    println!("cargo:rerun-if-changed={}", std_dir.display());

    let mut modules: Vec<(String, String)> = Vec::new();
    walk_yar(&std_dir, &std_dir, &mut modules);

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str("pub const STD_MODULES: &[(&str, &str)] = &[\n");
    for (name, file) in &modules {
        out.push_str(&format!(
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/lib/std/{file}\"))),\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("std_modules.rs"), out).unwrap();
}

/// Recursively collect `*.yar` files under `dir`, recording each as
/// `(dotted module name, path relative to the std dir)`.
fn walk_yar(dir: &Path, std_dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut files: Vec<String> = entries
        .filter_map(|e| e.ok())
        .filter(|e| {
            let p = e.path();
            p.is_file() && p.extension().is_some_and(|x| x == "yar")
        })
        .map(|e| {
            e.path()
                .strip_prefix(std_dir)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();
    files.sort();
    for file in files {
        let dotted = file.strip_suffix(".yar").unwrap().replace('/', ".");
        out.push((format!("std.{dotted}"), file));
    }
    // Recurse into subdirectories so nested module files remain possible.
    if let Ok(entries) = fs::read_dir(dir) {
        let mut subdirs: Vec<_> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.path())
            .collect();
        subdirs.sort();
        for sub in subdirs {
            walk_yar(&sub, std_dir, out);
        }
    }
}
