[package]
name = "yarrow_core"
version = "0.1.0"
edition = "2024"

[dependencies]
half = "2.4"
yarrow_runtime = { path = "../yarrow-runtime" }
cranelift-codegen = "0.133"
cranelift-frontend = "0.133"
cranelift-jit = "0.133"
cranelift-module = "0.133"
cranelift-native = "0.133"
cranelift-object = "0.133"
cranelift-control = "0.133"
