local Tokens = {
    LEFT_PAREN = {},
    RIGHT_PAREN = {},
    LEFT_CURLY = {},
    RIGHT_CURLY = {},
    LEFT_SQUARE = {},
    RIGHT_SQUARE = {},

    PLUS = {},
    MINUS = {},
    ASTERISK = {},
    SLASH = {},
    SLASH_SLASH = {},
    PERCENT = {},
    CARET = {},
    DOT = {},
    QUESTION = {},
    EXCLAMATION = {},
    AMPERSAND = {},
    BAR = {},
    COLON = {},
    SEMI_COLON = {},
    COMMA = {},

    EQUAL = {},
    EQUAL_EQUAL = {},
    NOT_EQUAL = {},
    GREATER = {},
    GREATER_EQUAL = {},
    LESS = {},
    LESS_EQUAL = {},

    IDENTIFIER = {},
    STRING = {},
    RUNE = {},
    INTEGER = {},
    FLOAT = {},
    BOOLEAN = {},
    TYPE = {},

    AND = {},
    OR = {},
    XOR = {},
    NOT = {},
    LEFT_SHIFT = {},
    RIGHT_SHIFT = {},

    IF = {},
    ELSE = {},
    WHILE = {},
    FOR = {},
    BREAK = {},
    CONTINUE = {},
    MATCH = {},
    CASE = {},

    UNWRAP = {},
    HANDLE = {},

    FUNCTION = {},
    RETURN = {},
    CALL = {},
    DO = {},
    WITH = {},

    CONST = {},
    STATIC = {},
    MUTABLE = {},
    SET = {},

    STRUCT = {},
    IMPLEMENT = {},
    ENUM = {},
    UNION = {},

    REQUIRE = {},
    DEFER = {},
    END = {},

    POP = {},
    DROP = {},
    DUP = {},
    OVER = {},
    ROT = {},
    SWAP = {},
}

return Tokens
