local Types = {
    I8 = {},
    I16 = {},
    I32 = {},
    I64 = {},
    I128 = {},
    U8 = {},
    U16 = {},
    U32 = {},
    U64 = {},
    U128 = {},
    F16 = {},
    F32 = {},
    F64 = {},
    F128 = {},
    STRING = {},
    RUNE = {},
    BOOL = {},
    VOID = {},
    ERROR = {},
    TYPE = {},
    ARRAY = {},
    LIST = {},
    HASHMAP = {},
    STACK = {},
    QUEUE = {},
    POINTER = {},
    REFERENCE = {},

    -- USIZE = {},
    -- ISIZE = {},
    -- C_CHAR = {},
    -- C_UCHAR = {},
    -- C_SHORT = {},
    -- C_USHORT = {},
    -- C_INT = {},
    -- C_UINT = {},
    -- C_LONG = {},
    -- C_ULONG = {},
    -- C_LONGLONG = {},
    -- C_ULONGLONG = {},
    -- C_FLOAT = {},
    -- C_DOUBLE = {},
    -- C_LONGDOUBLE = {},
}

return Types
