import enum


class Types(enum.Enum):
    I8 = enum.auto()
    I16 = enum.auto()
    I32 = enum.auto()
    I64 = enum.auto()
    I128 = enum.auto()
    U8 = enum.auto()
    U16 = enum.auto()
    U32 = enum.auto()
    U64 = enum.auto()
    U128 = enum.auto()
    F16 = enum.auto()
    F32 = enum.auto()
    F64 = enum.auto()
    F128 = enum.auto()
    STRING = enum.auto()
    RUNE = enum.auto()
    BOOL = enum.auto()
    VOID = enum.auto()
    ERROR = enum.auto()
    TYPE = enum.auto()
    ARRAY = enum.auto()
    LIST = enum.auto()
    HASHMAP = enum.auto()
    STACK = enum.auto()
    QUEUE = enum.auto()
    POINTER = enum.auto()
    REFERENCE = enum.auto()

    # NOTE: for C integrateion (?)
    USIZE = enum.auto()
    ISIZE = enum.auto()
    C_CHAR = enum.auto()
    C_UCHAR = enum.auto()
    C_SHORT = enum.auto()
    C_USHORT = enum.auto()
    C_INT = enum.auto()
    C_UINT = enum.auto()
    C_LONG = enum.auto()
    C_ULONG = enum.auto()
    C_LONGLONG = enum.auto()
    C_ULONGLONG = enum.auto()
    C_FLOAT = enum.auto()
    C_DOUBLE = enum.auto()
    C_LONGDOUBLE = enum.auto()
